version: '2'
services:
  afs-mysql:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    mem_limit: 2g
    cpus: 8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      # 指定初始化 sql 文件地址
      - /opt/mysql/init-sql:/docker-entrypoint-initdb.d
      # 指定 MySQL 数据目录
      - /opt/mysql/data:/var/lib/mysql

  afs:
    image: afs:v1
    ports:
      - 8080:8080
    depends_on:
      - afs-mysql
    links:
      - afs-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://afs-mysql:3306/aifuxiaosheng?autoReconnect=true&useSSL=false&allowMultiQueries=true&useTimezone=true&s&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
  
  afs-web:
    image: afs-web:v1
    depends_on:
      - afs
    links:
      - afs
    ports:
      - 80:80